<!-- 
```{r modelcomparisons, results = 'asis'}
looc <- read_csv("../results/loo_results_consonants.csv") %>%
  select(Model, elpd_diff, se_diff) %>%
  mutate(elpd_diff = round(elpd_diff,2),
         se_diff = round(se_diff,2)) 


loot <- read_csv("../results/loo_results_tapping.csv") %>%
  select(model, elpd_diff, se_diff) %>%
  mutate(elpd_diff = round(elpd_diff,2),
         se_diff = round(se_diff,2)) 


loo_all <- bind_cols(looc[-6,], loot) %>%
  unite(col = "Cons", elpd_diff, se_diff, sep = " (") %>%
  mutate(Cons = paste0(Cons, ")")) %>%
  unite(col = "Tap", elpd_diff1, se_diff1, sep = " (") %>%
  mutate(Tap = paste0(Tap, ")")) %>%
  rename(Model = model)# %>%
  #mutate(Model = recode(Model, ARK1 = "M3",
  #                             LMMbigramintercepts = "M1",
  #                             LMMbigramslopes = "M2",
  #                             ARKtarget = "M4",
  #                             ARKMoG = "M5",
  #                             ARKtargetMoG = "M6"))

names(loo_all)[c(2,4)] <- rep("$\\widehat{elpd}$ (SE)", 2)

papaja::apa_table(loo_all,
                  align = c("l", "r", "l", "r"), 
                  escape = FALSE, 
                  digits = 0,
                  stub_indents = list(`All models` = c(1:3), 
                                      `Indv. comparisons` = c(4:5)),
                  placement = "h",
                  col_spanners = list(`Consonants task` = c(1,2), `Tapping task` = c(3,4)),
                  caption = "Model comparisons in $\\Delta\\widehat{elpd}$ with SE in parentheses."
                  )
```
-->
```{r models, results = 'asis'}
An overview of all models can be found in Table \ref{tab:models}.

models <- tibble(Models = paste0("M",1:4),
       Type = c("LMM", "AR", "MoG", "AR + MoG"),
   #    Equation = paste0("\ \\ref{eq:", c("lmm", "lmmslopes", "ark", "arktarget", "arkmog", "arktargetmog"), "}"),
       Description = c("Random intercepts for bigram order and ppts",
                       "$\\phi$ for previous keystrokes (random intercepts for ppts only)",
                       "Slowdown $\\delta$ with probability $\\theta$ (random intercepts as in M1)",
                       "Combination of M2 and M3")
                       ) 

papaja::apa_table(models,
                  align = c("l", "l", "l"), 
                  escape = FALSE, 
                  digits = 0,
                  placement = "h",
                  caption = "Model overview. All models were fitted with random intercepts for participants.",
                  note = "LMM = linear mixed effects models; AR = Autoregressive model; MoG = Mixture of (log-)Gaussians"
                  ) 
```

